### ISSUE TITLE
in-virtualenv - cache virtualenvs by default

### ISSUE THREAD

**Issue by e3krisztian** [krisztianfekete/with-env#3]
Motivation: speed up `in-virtualenv`.

By default create virtualenvs inside `~/.cache/virtualenvs`
with SHA1 hashes of `requirements.txt`-s as virtualenv names

This would trigger addition of several options:

`--recreate`
`--no-cache`
`--clear-cache`

**Comment by krisztianfekete** [comment]
several identical `requirements.txt`-s with `'-e .'` in them will be differentiated

proposed solution: key generation for cache should include the path + content of `requirements.txt`
